const AuthActionTypes = {
  USER_SIGNIN_START: 'USER_SIGNIN_START',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',
  USER_SIGNOUT_START: 'USER_SIGNOUT_START',
  USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS',
  USER_SIGNOUT_FAILURE: 'USER_SIGNOUT_FAILURE',
};

export default AuthActionTypes;
